services:

  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: verticallogistica
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: verticallogisticadb
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  vertical-logistica-service:
    build:
      context: .
      dockerfile: Dockerfile

    image: vertical-logistica-service
    ports:
    - "8080:8080"

    depends_on:
      db:
        condition: service_healthy
